### ISSUE TITLE
letsencrypt taks fails if renewal is not necessary

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/yuca#1]
RUNNING HANDLER [letsencrypt : generate cert] ***********************************************************************
fatal: [yuca.yunity.org]: FAILED! => {"changed": true, "cmd": ["/root/simp_le/venv/bin/simp_le", "-f", "account_key.json", "-f", "fullchain.pem", "-f", "key.pem", "--email", "mail@yunity.org", "-d", "dev.karrot.world", "-d", "dev.foodsaving.world", "-d", "devdev.foodsaving.world", "-d", "karrot-dev.foodsaving.world", "-d", "dev.yunity.org", "-d", "mvp-proposal.yunity.org", "--default_root", "/var/www/html", "--tos_sha256", "cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b"], "delta": "0:00:04.816739", "end": "2017-12-23 13:08:54.920490", "msg": "non-zero return code", "rc": 1, "start": "2017-12-23 13:08:50.103751", "stderr": "2017-12-23 12:08:54,887:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.", "stderr_lines": ["2017-12-23 12:08:54,887:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1."], "stdout": "", "stdout_lines": []}

**Comment by nicksellen** [comment]
It should only be running that handler if the dns entries have changed, but that error sounds like it is saying the dns entries have not changed.

**Comment by tiltec** [comment]
ah yes, that might be a special case: I changed the dns entry on the server, then got a new certificate. later on I ran ansible with these settings. it changed in ansible's eyes, but it's the same for let's encrypt.

Essentially that means: don't change files on the server that are managed by ansible.

**Comment by nicksellen** [comment]
"ansibles eyes" should just be the contents of the file, so perhaps the ordering was different. It isn't the end of the world to change things on the server...

**Comment by tiltec** [comment]
different ordering might have been the reason
