### ISSUE TITLE
Implement permissions using acls

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/yuca#10]
Our current permissions system is a bit broken (site user, site deploy user, and www-data user) at the moment (at least for karrot), could implement it in a nicer way using acls [1] so the users get exactly the permissions they need.

[1] http://docs.ansible.com/ansible/latest/acl_module.html

**Comment by tiltec** [comment]
I spend a day or so to set up ACLs, the result can be seen in https://github.com/yunity/yuca/commit/732ac60730e117f776e95c30dc05f127f34dc2b2
It seems worth to get them right, but it's also quite fiddly. Things to look out for:

- there's the ACL mask that dictates the effective permissions. they can be less than the given permissions. I set the mask to `rwx` to get no surprises.
- newly created files need to receive default ACLs, so be sure to set them
- existing files should be handled as well
- to make them readable to nginx, parent directories need to have `x` permissions

My current permission setup:
- `/var/www/karrot-dev/www` owned by `karrot-dev`, readable by `www-data` and `karrot-dev-deploy`
- `/var/www/karrot-dev/www/backend` owned by `karrot-dev-deploy`, readable by `karrot-dev`
- `/var/www/karrot-dev/www/static` owned by `karrot-dev-deploy`, readable by `www-data`
- `/var/www/karrot-dev/www/uploads` owned by `karrot-dev`, readable by `www-data`

**Comment by tiltec** [comment]
We could set all directories and subdirectories in `/var/www` to be world-executable to avoid some extra permissions declarations and surprises.

**Comment by tiltec** [comment]
Seems to work for dev.karrot.world and karrot.world
